#!/bin/sh /etc/rc.common
# Copyright (C) 2023 Waytix Team

START=99
STOP=10

USE_PROCD=1
PROG=/usr/sbin/waytixd

start_service() {
    procd_open_instance
    procd_set_param command "$PROG"
    procd_set_param respawn
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}

stop_service() {
    killall xray 2>/dev/null
}

reload_service() {
    stop
    start
}

boot() {
    # Создаем конфиг, если его нет
    uci -q get waytix.config || uci set waytix.config=waytix
    uci commit waytix
    
    # Запускаем сервис
    start
}
